name: Rust

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: cargo build --verbose
    # Disabled to current compiler problems :/ https://github.com/rust-lang/rust/issues/64266
    #- name: Run tests
    #  run: cargo test --verbose
    - name: Build release
      run: cargo build --release --verbose
    - name: Upload bin
      uses: actions/upload-artifact@v1.0.0
      with:
        # Artifact name
        name: OSM_to_Euroscope
        # Directory containing files to upload
        path: target/release/OSM_to_Euroscope
